spring:
  application:
    name:
      location-writer-client
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/location
    username: location
    password: location
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: POSTGRESQL
    #    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/location
    schemas: public
    user: location
    password: location
    locations: classpath:db/migration

server:
  port: 0

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true

location:
  async:
    core-pool-size: 2
    max-pool-size: 100
    queue-capacity: 10000
  datasource:
    host:
      ${DATABASE_HOST:localhost}
    port:
      ${DATABASE_PORT:5433}
    database:
      location
    username:
      location
    password:
      location
  kafka:
    bootstrap-server: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    location-topic: location
    consumer:
      group-id: jitpay
