version: '2'
services:
  location-writer-db:
    image: postgres:12
    environment:
      POSTGRES_USER: location
      POSTGRES_PASSWORD: location
#      POSTGRES_DB: jitpaydb
    ports:
      - 5433:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - data_location_writer:/var/lib/postgresql/data

volumes:
  data_location_writer:
    driver: local

