version: '2'
services:
  location-db:
    image: postgres:12
    environment:
      POSTGRES_USER: location
      POSTGRES_PASSWORD: location
#      POSTGRES_DB: jitpaydb
    ports:
      - 5433:5432
    volumes:
      - data_location:/var/lib/postgresql/data

volumes:
  data_location:
    driver: local

